#ifndef ERRORS_H
#define ERRORS_H

#define EXIT_NO_ERRORS 0
#define EXIT_WRONG_ARG_COUNT 1
#define EXIT_BAD_FILENAME 2
#define EXIT_BAD_MAGIC_NUMBER 3
#define EXIT_BAD_COMMENT_LINE 4
#define EXIT_BAD_DIMENSIONS 5
#define EXIT_BAD_MAX_GRAY_VALUE 6
#define EXIT_MALLOC_FAIL 7
#define EXIT_BAD_DATA 8
#define EXIT_ERROR_OUTPUT_FAIL 9
#define EXIT_BAD_LAYOUT 10
#define EXIT_MISCELLANEOUS 100

#endif